# Site settings
title: Jesus E. Larios Murillo
email: preparedfortherain@gmail.com
description: >-
  Random tutorials and documentation that are useful to me, and may be useful to others.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  larioj

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
